### ISSUE TITLE
SPICE BSP files should be usable without needing the ANISE file equivalent

### ISSUE THREAD

**Issue by ChristopherRabotin** [anise-toolkit/anise.rs#30]
# Use case
Although the ANISE file format provides a number of advantages compared to the BSP files, requiring users to convert their data into ANISE before using this library is a large overhead.

# Effort
ANISE.rs already supports reading BSP files of some types. However, that implementation requires memory allocations. These should not be required.

Hence, the crux of this issue is to rewrite the SPK parser to not perform any memory allocations. This issue also includes providing a rewrite of some of the SPK related functions (exact list to be determined from [this list](https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/C/cspice/index.html#S)). These functions must be behind a specific crate feature, e.g. `spice-interop`.

# Verification

_TDB_: from the list of functions above, the tests should require `rust-spice` by @GregoireHENRY and make sure that the SPK functions selects return the same values. This will likely require #26 too.

**Comment by GregoireHENRY** [comment]
I will make sure the list of SPK-related selected functions are supported in the wrapper.

**Comment by ChristopherRabotin** [comment]
The latest update can load SPK and BPC data using `furnsh_spk` and `furnsh_bpc`. I can't make those generic yet because the data is strongly typed at loading time (in order to correctly read the summary data) and they go into different variables.
